services:
  intjsys-official:
    image: ccr.ccs.tencentyun.com/reallier/intjsys-official:latest
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intjsys-official.rule=Host(`intjsys.com`)"
      - "traefik.http.routers.intjsys-official.entrypoints=websecure"
      - "traefik.http.routers.intjsys-official.tls=true"
      - "traefik.http.routers.intjsys-official.tls.certresolver=myresolver"
      - "traefik.http.services.intjsys-official.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
