services:
  intjsys-official:
    image: ccr.ccs.tencentyun.com/reallier/intjsys-official:latest
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.intjsys-official.rule=Host(`intjsys.com`)
      - traefik.http.routers.intjsys-official.entrypoints=websecure443
      - traefik.http.routers.intjsys-official.tls=true
      - traefik.http.routers.intjsys-official.tls.certresolver=myresolver
      - traefik.http.routers.intjsys-official-http.rule=Host(`intjsys.com`)
      - traefik.http.routers.intjsys-official-http.entrypoints=web
      - traefik.http.services.intjsys-official.loadbalancer.server.port=3000

networks:
  traefik:
    external: true
